name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build the Go application
      run: |
        go build -o go-ata-nop ./main.go

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/go-ata-nop:${{ github.ref_name }} .

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/go-ata-nop:${{ github.ref_name }}